export const DAILY_PROMO = {
  subtitle: "Hemat Besar",
  title: "Untuk Set Liburan",
  image: "/images/promo/daily-promo.png",
  link: "/shop/holiday-sets",
};

export const ESSENTIAL_PRODUCTS = [
  {
    id: "prod-1",
    name: "Hydrate Smoothing Serum",
    brand: "Lanure",
    category: "SERUM WAJAH",
    price: 4000,
    image: "/images/serum.png",
    rating: 4.8,
    reviewCount: 124,
    tags: ["Baru"],
    description: "Serum hidrasi untuk kulit halus.",
    shortDesc: "Serum hidrasi.",
    affiliateUrl: "#",
  },
  {
    id: "prod-2",
    name: "Luminous Glow Serum",
    brand: "Lanure",
    category: "SERUM WAJAH",
    price: 4500,
    image: "/images/serum-minimalist.jpg",
    rating: 4.9,
    reviewCount: 89,
    tags: [],
    description: "Dapatkan kilau bercahaya.",
    shortDesc: "Serum kilau.",
    affiliateUrl: "#",
  },
  {
    id: "prod-3",
    name: "Turmeric Purifying Mask",
    brand: "Lanure",
    category: "MASKER",
    price: 3500,
    image: "/images/body.png",
    rating: 4.7,
    reviewCount: 56,
    tags: ["Baru"],
    description: "Bersihkan kulit Anda dengan kunyit.",
    shortDesc: "Masker pembersih.",
    affiliateUrl: "#",
  },
  {
    id: "prod-4",
    name: "Velvet Matte Lipstick",
    brand: "Lanure",
    category: "MAKEUP",
    price: 2500,
    image: "/images/lipstick.png",
    rating: 4.6,
    reviewCount: 210,
    tags: [],
    description: "Hasil akhir matte yang halus seperti beludru.",
    shortDesc: "Lipstik matte.",
    affiliateUrl: "#",
  },
];
